[package]
name = "axum-cloudflare-adapter"
version = "0.4.0"
edition = "2021"
authors = ["Logan Keenan"]
description = "An adapter to easily allow an Axum server to be run within a Cloudflare worker."
rust-version = "1.67.1"
repository = "https://github.com/logankeenan/axum-cloudflare-adapter"
license = "MIT"
keywords = ["Cloudflare", "Axum", "WASM"]

[lib]
crate-type = ["cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.7", default-features = false }
worker = { version = "0.0.13 "}
http-body = "0.4.5"
axum-cloudflare-adapter-macros = { path = "../macros", version = "0.1.0" }

[dev-dependencies]
wasm-bindgen-test = "0.3.30"
wasm-bindgen-futures = "0.4.34"
wasm-bindgen = "0.2.84"

